### ISSUE TITLE
driver: persistent (and incorrect) "Trajectory start position doesn't match current robot position"

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/motoman#111]
observed behaviour: when trying to execute a trajectory through the `motoman_driver` provided `joint_trajectory_action` node, the motoros application persistently returns a `MotionReplySubcodes::Invalid::DATA_START_POS` error, even if `target_pos == current_pos` for all joints. Analysis of the simple message traffic between motoros and the ROS PC confirmed the receipt of the `DATA_START_POS` error message.

Starting the servos _before_ commanding a motion does not help (to avoid running into issues with `START_MAX_PULSE_DEVIATION` and gravity).

The work-around for #91 also does not influence this.

expected: execution of the trajectory

**Comment by gavanderhoorn** [comment]
tl;dr: ROS side of driver (incorrectly) assumes order of joint data in incoming goals is identical to what it is configured for / the joint order motoros expects, leading to all trajectories being refused because `current_pos == traj[0].target_pos` is never true.

---

It would appear the code in at least [JointTrajectoryAction::goalCB(JointTractoryActionServer::GoalHandle gh)](https://github.com/ros-industrial/motoman/blob/d17f65f60381590cee008776944129e7e1b893b2/motoman_driver/src/industrial_robot_client/joint_trajectory_action.cpp#L192) makes an assumption about the ordering of joint names in a `JointTrajectory` message when mapping such a message to an (internally used) `motoman_msgs::DynamicJointsGroup`.

The current implementation essentially does this in the following way:
1. find the index of the _first joint_ in the incoming trajectory the node knows about ([here](https://github.com/ros-industrial/motoman/blob/d17f65f60381590cee008776944129e7e1b893b2/motoman_driver/src/industrial_robot_client/joint_trajectory_action.cpp#L210-L214)). Note that the joints the node knows about are configured using the parameters loaded in the `sda10f_motion_interface.yaml` file ([here](https://github.com/ros-industrial/motoman/blob/7ab584221d10f4e9e07ed7624a3404de879276b2/motoman_sda10f_support/config/sda10f_motion_interface.yaml) for the SDA10)
2. if it finds that joint name in the goal msg, it saves its index ([here](https://github.com/ros-industrial/motoman/blob/d17f65f60381590cee008776944129e7e1b893b2/motoman_driver/src/industrial_robot_client/joint_trajectory_action.cpp#L210-L214)), and then proceeds by copying the incoming data into the corresponding `DynamicJointsGroup` fields, _under the assumption that data for consecutive joints in the kinematic chain of the robot is also stored at consecutive indices in the `positions`, `velocities` and `accelerations` arrays_

I've emphasised the problematic parts.

This is a dangerous assumption to make in any case, and for instance MoveIt appears to happily re-order joints when submitting goals, making looking for the 'first joint' completely pointless (as there is no guarantee that the order of joint target values in the goal now corresponds to anything on the robot side).

A correct(er?) approach would seem to be to perform the mapping for each joint individually, _every time_ a goal is received. That would mean `std::find(..)`ing `N` joints again and again, but there is no requirement for Action clients to maintain the same order of joints as those the server is configured with. It would appear the mapping can also not be cached (at least not be re-used for future incoming goals), as clients could potentially randomise the order in which they specify the joint data every submitted goal.

As the order of the joint targets in the `DynamicJointsGroup` after the mapping doesn't correspond to the state of the robot at the time the trajectory is executed, the motoros application returns the reported "_Trajectory start position doesn't match current robot position_". Only in (very) rare circumstances will the commanded trajectory actually be executed (if the re-ordered states happen to match because the joint positions of re-ordered joints are identical).

**Comment by gavanderhoorn** [comment]
This was reported by @jettan, @mbharatheesha and @de-vri-es.

**Comment by gavanderhoorn** [comment]
I'm not sure, but I think the above described assumption (about joint name ordering) is (at least partly) why the joints and links in fi the `motoman_sda10f` and the `motoman_sia10d` xacro macros are named like `link_N_A` and `joint_N_A` (with `N` an increasing number, and `A` the name of the joint conforming to Motoman specs).

[Here](https://github.com/ros-industrial/motoman/blob/5c58be32132205e2e62b39858fde8330bcbdcf4a/motoman_sda10f_support/urdf/arm_macro.xacro#L118) for the SDA10F, and [here](https://github.com/ros-industrial/motoman/blob/jade-devel/motoman_sia10f_support/urdf/sia10f_macro.xacro#L136) for the SIA10F.

**Comment by gavanderhoorn** [comment]
@thiagodefreitas: any input?

**Comment by gavanderhoorn** [comment]
I think this is a serious bug, and am considering adding a warning / notice to the wiki page telling prospective users about it.

Thoughts @shaun-edwards ?

**Comment by gavanderhoorn** [comment]
Just thought I'd add this: this exact issue seems to also have been reported by @thiagodefreitas in https://github.com/ros-industrial/motoman/pull/42#issuecomment-54307172:

> Although motoman joints are usually named as joint_letter, I have an issue when running both drivers(even the current state of the older one from ros-i hydro-devel), where I can not work properly with MoveIt!. I would suggest that an issue is created to investigate this problem with the alphabetical order. For the moment, I have kept it on the URDF as joint_number_letter to avoid this problem.

That would seem to suggest the assumption about `s` being the first joint and then `++`-ing through the rest of the joints was also already present in "the older one from ros-i hydro-devel".

**Comment by tanimfresh** [comment]
hi @gavanderhoorn , 

I believe I am experiencing this issue using a Yaskawa GP8 and YRC1000 micro controller w/ MoveIt. 
Is the suggested workaround the fix that you mentioned to the jointtrajectoryaction.cpp? 

"A correct(er?) approach would seem to be to perform the mapping for each joint individually, every time a goal is received. That would mean std::find(..)ing N joints again and again, but there is no requirement for Action clients to maintain the same order of joints as those the server is configured with. It would appear the mapping can also not be cached (at least not be re-used for future incoming goals), as clients could potentially randomise the order in which they specify the joint data every submitted goal."

**Comment by gavanderhoorn** [comment]
@tanimfresh: first thing to make sure is you get this error from the driver and not from MoveIt itself. MoveIt has added a similar check.

I would suggest to check the origin of the error first, before thinking about changing the driver' source.

If you add this line to your `.bashrc`, and then open a new terminal and try testing again, it should tell you which node prints this error:

```bash
export ROSCONSOLE_FORMAT='[${severity}] [${time}] [${node}] [${logger}]: ${message}'
```

**Comment by tanimfresh** [comment]
Hi @gavanderhoorn, 

I believe after adding this logging that the error is indeed coming from the driver: 
```

header: 
  seq: 21
  stamp: 
    secs: 1586803189
    nsecs: 399154532
  frame_id: ''
level: 2
name: "/motion_streaming_interface"
msg: "Receiving joint trajectory message"
file: "/home/tanim/vlr-workspace/vlr-software/src/gp8/motoman/motoman_driver/src/industrial_robot_client/joint_trajectory_streamer.cpp"
function: "joint_trajectory_streamer::JointTrajectoryStreamer::jointTrajectoryCB"
line: 128
topics: [/rosout]
---
header: 
  seq: 21
  stamp: 
    secs: 1586803189
    nsecs: 397491854
  frame_id: ''
level: 2
name: "/joint_trajectory_action"
msg: "Received new goal"
file: "/home/tanim/vlr-workspace/vlr-software/src/gp8/industrial_core/industrial_robot_client/src/joint_trajectory_action.cpp"
function: "joint_trajectory_action::JointTrajectoryAction::goalCB"
line: 112
topics: [/rosout, /joint_path_command, /joint_trajectory_action/result, /joint_trajectory_action/feedback,
  /joint_trajectory_action/status]
---
header: 
  seq: 22
  stamp: 
    secs: 1586803189
    nsecs: 399592249
  frame_id: ''
level: 8
name: "/motion_streaming_interface"
msg: "Validation failed: Trajectory doesn't start at current position."
file: "/home/tanim/vlr-workspace/vlr-software/src/gp8/motoman/motoman_driver/src/joint_trajectory_streamer.cpp"
function: "joint_trajectory_streamer::MotomanJointTrajectoryStreamer::is_valid"
line: 504
topics: [/rosout]
---
header: 
  seq: 22
  stamp: 
    secs: 1586803189
    nsecs: 397686828
  frame_id: ''
level: 2
name: "/joint_trajectory_action"
msg: "Publishing trajectory"
file: "/home/tanim/vlr-workspace/vlr-software/src/gp8/industrial_core/industrial_robot_client/src/joint_trajectory_action.cpp"
function: "joint_trajectory_action::JointTrajectoryAction::goalCB"
line: 145
topics: [/rosout, /joint_path_command, /joint_trajectory_action/result, /joint_trajectory_action/feedback,
  /joint_trajectory_action/status]
---
header: 
  seq: 23
  stamp: 
    secs: 1586803189
    nsecs: 421066315
  frame_id: ''
level: 2
name: "/joint_trajectory_action"
msg: "Waiting to check for goal completion until halfway through trajectory"
file: "/home/tanim/vlr-workspace/vlr-software/src/gp8/industrial_core/industrial_robot_client/src/joint_trajectory_action.cpp"
function: "joint_trajectory_action::JointTrajectoryAction::controllerStateCB"
line: 232
topics: [/rosout, /joint_path_command, /joint_trajectory_action/result, /joint_trajectory_action/feedback,
  /joint_trajectory_action/status]

```

In this case, is the only solution at the moment the method you proposed of changing the driver source? 
I am also curious as to whether point streaming method introduced in PR 215 may help, as I am planning on implementing this regardless for better closed loop control

**Comment by gavanderhoorn** [comment]
> In this case, is the only solution at the moment the method you proposed of changing the driver source?

No. The right thing to do would be to diagnose what causes the error to be printed.

There's no point in haphazardly starting to edit files without knowing the cause.

First thing to check: are you using [motoman_gp8_support/urdf/gp8_macro.xacro](https://github.com/ros-industrial/motoman/blob/26d739bec0ed307557bdc5be07f0f30a04ac55a2/motoman_gp8_support/urdf/gp8_macro.xacro) as URDF, or something you created yourself?

If you're using something you created yourself, you'll want to compare with [motoman_gp8_support/urdf/gp8_macro.xacro](https://github.com/ros-industrial/motoman/blob/26d739bec0ed307557bdc5be07f0f30a04ac55a2/motoman_gp8_support/urdf/gp8_macro.xacro), specifically how the joint names are defined. You'll also want to make sure you use the same joint names in your MoveIt configuration, and make sure to use the correct joint names there as well.

For single group setups with a known-good robot model, the error reported in the OP here should not occur, provided the work-around (including a nr in the joint names) is used.

That's the reason I'd like to understand why you are running into this.

Besides checking which `.xacro` you are using, it would also be good to post a single `JointState` message here, so we can compare.

> I am also curious as to whether point streaming method introduced in PR 215 may help, as I am planning on implementing this regardless for better closed loop control

No, that's not going to help. And please be aware of #219 and #252.

**Comment by tanimfresh** [comment]
Hi @gavanderhoorn , 

I am indeed using a different urdf generated by MoveIt. I compared it with the typical gp8_macro.xacro and it looks like the MoveIt setup assistant just appends additional information to this URDF; the joint names are identical. I have included an example of a JointState message below:

```
---
header: 
  seq: 429
  stamp: 
    secs: 1586841581
    nsecs: 301554218
  frame_id: ''
name: [joint_1_s, joint_2_l, joint_3_u, joint_4_r, joint_5_b, joint_6_t]
position: [0.0, -8.628642535768449e-05, 1.4999072551727295, 8.181230805348605e-05, 2.3968450477696024e-05, 3.7544981751125306e-05]
velocity: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
effort: []
---

```

> For single group setups with a known-good robot model, the error reported in the OP here should not occur, provided the work-around (including a nr in the joint names) is used.

Can you please elaborate this workaround? I did not catch this explanation.
