### ISSUE TITLE
Problem operating multiple robot groups at the same time (CSDA10F)

### ISSUE THREAD

**Issue by Danfoa** [ros-industrial/motoman#251]
Good day,
After following the configuration instructions to use a dual arm Motoman Robot, the CSDA10F, we have encountered a small problem while operating the 15 DOF at the same time, we get an error stating that the start point of the `joint_path_command` is not the same as the start pose of the robot. 

After digging into the problem I know the source of the issue but not how to solve it. The `joint_path_command` always cero one or the two torso joints (one is a mirror of the other in the URDF). Which triggers the error when the `motion_streaming_interface` checks the start state.

The support package of the CSDA10F was uploaded by us and can be found [here](https://github.com/Danfoa/invite-robotics/tree/developmental/invite_motoman_support), where the [joint_names_csda10f.yaml](https://github.com/ros-industrial/motoman_experimental/tree/kinetic-devel/motoman_csda10f_support/config), and [csda10f_motion_interface.yaml](https://github.com/ros-industrial/motoman_experimental/tree/kinetic-devel/motoman_csda10f_support/config) are. 

Also the moveit [controller.yaml ](https://github.com/Danfoa/invite-robotics/tree/developmental/invite_motoman_moveit_config/config) configuration we use is here.

Here is the planning command for a 15 DOF motion with the move group `csda10f`, as you see the last group, which corresponts to one of the torso joints, is cero out. 
```
rostopic echo /joint_path_command
header: 
  seq: 0
  stamp: 
    secs: 1540804125
    nsecs: 866326580
  frame_id: "/base_link"
joint_names: [arm_left_joint_1_s, arm_left_joint_2_l, arm_left_joint_3_e, arm_left_joint_4_u, arm_left_joint_5_r,
  arm_left_joint_6_b, arm_left_joint_7_t, arm_right_joint_1_s, arm_right_joint_2_l,
  arm_right_joint_3_e, arm_right_joint_4_u, arm_right_joint_5_r, arm_right_joint_6_b,
  arm_right_joint_7_t, torso_joint_b1, torso_joint_b2]
points: 
  - 
    num_groups: 4
    groups: 
      - 
        group_number: 0
        num_joints: 7
        valid_fields: 0
        positions: [-0.2465789020061493, 1.3706119060516357, 0.042617324739694595, -0.6750122904777527, 3.111323118209839, 1.1329739093780518, 2.3026256561279297]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: 
          secs: 0
          nsecs:         0
      - 
        group_number: 1
        num_joints: 7
        valid_fields: 0
        positions: [-0.3837849795818329, 0.3498840034008026, -0.48697054386138916, -0.799386203289032, -0.6211710572242737, -0.8425199389457703, -2.3632328510284424]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: 
          secs: 0
          nsecs:         0
      - 
        group_number: 2
        num_joints: 1
        valid_fields: 0
        positions: [-1.2986000776290894]
        velocities: [0.0]
        accelerations: [0.00032456790385969195]
        effort: [0.0]
        time_from_start: 
          secs: 0
          nsecs:         0
      - 
        group_number: 3
        num_joints: 1
        valid_fields: 0
        positions: [0.0]                # This is the error, position, and acceleration should be the same as the joint above.
        velocities: [0.0]
        accelerations: [0.0]
        effort: [0.0]
        time_from_start: 
          secs: 0
          nsecs:         0
  - 
```
And when I use a motion group that plans only for the two arms (not base), the same error ocures but this time the `/joint_path_command` topic sends a message just like the one above but with both torso joints cero out. I am not even sure if the torso joints should appear in this case since we are not planning for them.

Can anyone please enlight me on the source of the issue? 

PS: Joint states are currently working perfectly, I can acquire the complete robot state, and we are able to move the move groups of 'arm_right', 'arm_left' and 'torso' separately but not combined.

This issue is related to #217,but this time I am personally at the robot and noticed the error source.
