### ISSUE TITLE
How to move two arms of dual arm robots simultaneously?

### ISSUE THREAD

**Issue by zhangOSK** [ros-industrial/motoman#342]
Hello!  I want to move both of arms of SDA5F but I am not sure how to deal with the groups of the dual arm robot.

 I am using ROS kinetic and FS100 controller. The config file of `sda5f_motion_interface.yaml` is shown below:

```yaml
topic_list:
    - name: sda5f_r1_controller
      ns: sda5f
      group: 0
      joints: ['arm_left_joint_1_s','arm_left_joint_2_l','arm_left_joint_3_e','arm_left_joint_4_u','arm_left_joint_5_r','arm_left_joint_6_b','arm_left_joint_7_t']
    - name: sda5f_r2_controller
      ns: sda5f
      group: 1
      joints: ['arm_right_joint_1_s','arm_right_joint_2_l','arm_right_joint_3_e','arm_right_joint_4_u','arm_right_joint_5_r','arm_right_joint_6_b','arm_right_joint_7_t']
    - name: sda5f_b1_controller
      ns: sda5f
      group: 2
      joints: ['torso_joint_b1']
    - name: sda5f_b2_controller
      ns: sda5f
      group: 3
      joints: ['torso_joint_b2']
```

I am using python to publish joints data to the robot. After checking the issues before, I use 
`client = actionlib.SimpleActionClient('joint_trajectory_action', FollowJointTrajectoryAction)` 
 to send goal of  `goal = FollowJointTrajectoryGoal()`.  

The problem is that I don't know how to send 4 groups of joints information into the goal. I know that we can add points to goal by

```python
goal.trajectory.points.append(JointTrajectoryPoint(positions=q0,
        velocities=qdot, time_from_start=rospy.Duration( 0.0)))
```

But what if I want to send the joints information of `torso_joint_b1`, `torso_joint_b2` and joints of both left and right arm at the same time?

Could you please tell me how to do that?
