### ISSUE TITLE
Cannot move GP4 + YRC1000micro with ROS using `rostopic pub` or MoveIt + RViz configuration

### ISSUE THREAD

**Issue by adamlouis** [ros-industrial/motoman#472]
Hi! I am trying to get a new **GP4** robot working with **ROS + MoveIt** using a **YRC1000micro** controller.

I can't get to the robot to move ... but I seem close. I would appreciate any help or debugging steps to get our robot moving.

We purchased our robot with the ROS package installed.

## summary
- I am running ros noetic on ubuntu 20.04 (LTS)
- I can read the robot state & view it in Rviz
- MoveIt commands from Rviz yield error:
  - `Failed to initialize MotoRos motion, trajectory execution ABORTED. If safe, call the 'robot_enable' service to (re-)enable Motoplus motion and retry.`
 - `rostopic` commands fail with the same error
- I already called `rosservice call /robot_enable "{}"` and calling it again does not change the behavior
- I can start servos & run jobs using the ethernet protocol

Why can't I move the robot?

What simple test can I run to verify configuration of remote control of the GP4 over ROS with the YRC1000?

### 1. set up motoman driver

First, I followed the instructions here: https://wiki.ros.org/motoman_driver/Tutorials/Usage

I start roscore in terminal 1

**terminal 1**
```
roscore
```

then, I load the gp4 urdf & joint names

**command terminal**
```
roslaunch motoman_gp4_support load_gp4.launch
rosparam set controller_joint_names "[joint_1_s,joint_2_l,joint_3_u,joint_4_r,joint_5_b,joint_6_t]"
```

then, I run the driver for our controller w/ the robot's pre-set IP 

**terminal 2**
```
roslaunch motoman_driver robot_interface_streaming_yrc1000.launch robot_ip:=192.168.1.31
```

### 2. run a moveit config 

next, I run my move it configuration.

I adapted my configuration from this one in `motoman_experimental`: https://github.com/ros-industrial/motoman_experimental/tree/kinetic-devel/motoman_mpl80_moveit_config

My modifications were:
    - replace `mpl80` with `gp4`
    - replace `motoman_mpl_support` with `motoman_gp4_support`
    - replace `mpl80` urdf & srdf with `gp4` urdf & srdf
    - remove components that duplicate the interface streaming above
    - remove `fake_execution` and `sim`  ... because I am trying to test a real robot
    - remove db ... don't need it for my test

I forked the `motoman_experimental` repo and created a branch here with my motoman_gp4_moveit_config configuration: https://github.com/adamlouis/motoman_experimental/tree/motoman_gp4_moveit_config/motoman_gp4_moveit_config

I would be happy to clean that up & find a way to include it in motoman_experimental when I figure out what's wrong.

then, I run it with
  
**terminal 3**
```
roslaunch motoman_gp4_moveit_config demo.launch
```

at this point, if I move the robot using our teach pendant, the movement is reflected in Rviz.

this is good & tells me that I am able to read state from the yrc1000micro.

### 3. prepare for execution

now, I am ready to move the robot

**command terminal**
```
rosservice call /robot_enable "{}"
```

I hear relays click and see the servo lights turn on

output in **command terminal** 
```
success: True
message: "Motoman robot is now enabled and will accept motion commands."
```

output in **terminal 2**
```
Motoman robot is now enabled and will accept motion commands.
```

This is good - in theory, I can move the robot.

### 4. Try to move with RViz + MoveIt

I try to move the robot 2 ways & get the same behavior.

First, in Rviz + MoveIt, I set a goal position. I choose a goal position only small distance from the current position. I click "Plan" and "Execute".

On "Execute", I get the following output:

**output in terminal 2** 
```
Failed to initialize MotoRos motion, trajectory execution ABORTED. If safe, call the 'robot_enable' service to (re-)enable Motoplus motion and retry.
```

**output in terminal 3** 
```
Controller is taking too long to execute trajectory (the expected upper bound for the trajectory execution was 2.526993 seconds). Stopping trajectory.
```

If I run the command to enable the service

**command terminal**
```
rosservice call /robot_enable "{}"
```

& repeat the above steps, I get the same error.

### 5. Try to move with `rostopic`

It's possible I wrote a bad moveit config, so I try to run some trivial command to move the robot with ROS.

The easiest thing seemed like: `rostopic pub /joint_trajectory_action/goal control_msgs/FollowJointTrajectoryActionGoal `. Is there some simpler command to test "write" commands to the yrc1000 over ROS?

This command fails with the same errors as above:

**output in terminal 2** 
```
Failed to initialize MotoRos motion, trajectory execution ABORTED. If safe, call the 'robot_enable' service to (re-)enable Motoplus motion and retry.
```

**output in terminal 3** 
```
Controller is taking too long to execute trajectory (the expected upper bound for the trajectory execution was 2.526993 seconds). Stopping trajectory.
```

Here's my full command. The positions I provide are the robot's current positions.

```
rostopic pub /joint_trajectory_action/goal control_msgs/FollowJointTrajectoryActionGoal "header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
goal_id:
  stamp:
    secs: 0
    nsecs: 0
  id: ''
goal:
  trajectory:
    header:
      seq: 0
      stamp:
        secs: 0
        nsecs: 0
      frame_id: ''
    joint_names:
    - joint_1_s
    - joint_2_l
    - joint_3_u
    - joint_4_r
    - joint_5_b
    - joint_6_t
    points:
    - positions: [0.10212502628564835, 0.10033370554447174, 0.05954036861658096, 0.007940606214106083, -1.3190429210662842, 4.0864481925964355]
      velocities: [0,0,0,0,0,0]
      accelerations: [0,0,0,0,0,0,0]
      effort: [0,0,0,0,0,0]
      time_from_start: {secs: 0, nsecs: 0}
  path_tolerance:
  - {name: '', position: 0.0, velocity: 0.0, acceleration: 0.0}
  goal_tolerance:
  - {name: '', position: 0.0, velocity: 0.0, acceleration: 0.0}
  goal_time_tolerance: {secs: 0, nsecs: 0}"
```

Some notes:
- `INIT_ROS` is the "Current Job" on the teach pendant
- the green "Servo" light on the teach pendant is on
- the key in the teach pendant is switched to remote mode
- I can turn servos on and start jobs with the ethernet commands `SVO` and `START` - which implies to me remote control is ok
- I have not confirmed that `CMD REMOTE SEL` is set to "valid" in the pseudo input display per page 22 / 291 of the "YRC1000micro OPTIONS INSTRUCTIONS for Ethernet Function". We have a different teach pendant than is referenced in the documentation & I have not found this setting. Is this related? I suspect I am ok, since I could start jobs over the ethernet protocol
- I get 3 errors / warnings when starting `robot_interface_streaming_yrc1000.launch`. The warnings seem fine & the errors seems fine per @gavanderhoorn's reply in https://github.com/ros-industrial/motoman/issues/242 & https://github.com/ros-industrial/motoman/issues/235 ... 

```
[ERROR] [1647042622.182945880]: Failed to find topic_list parameter
[ WARN] [1647042622.190244041]: Failed to get '~port' parameter: using default (50242)
[ERROR] [1647042622.194533748]: Failed to find topic_list parameter
[ WARN] [1647042622.210121014]: Tried to connect when socket already in connected state
```

Thanks for reading & thanks in advance for any help! Would appreciate any pointers to help get us up an running.
