### ISSUE TITLE
Trajectory start position doesn't match current robot position (3011) when using multiple groups

### ISSUE THREAD

**Issue by riv-dpowell** [ros-industrial/motoman#585]
We are trying to control a GP25 and 2 axis positioner with a YRC1000 controller using ROS. We are using the job: https://github.com/ros-industrial/motoman/blob/kinetic-devel/motoman_driver/Inform/DX200%2C%20FS100%2C%20YRC1000/single_arm_with_base_axis/INIT_ROS.JBI on the controller.

We are using 2 control groups like this

```
---
topic_list:
  - name: robot
    ns: ""
    group: 0
    joints:
      - yaskawa_joint_1_s
      - yaskawa_joint_2_l
      - yaskawa_joint_3_u
      - yaskawa_joint_4_r
      - yaskawa_joint_5_b
      - yaskawa_joint_6_t
  - name: positioner
    ns: ""
    group: 1
    joints:
      - yaskawa_joint_7_p
      - yaskawa_joint_8_y
```

and using the multi group launch file:
<include file="$(find motoman_driver)/launch/robot_multigroup_interface_streaming_yrc1000.launch">

echoing the /joint_state topic shows the robot and positioner joints as expected.

When sending trajectories to the controller we're getting errors like:

[15:48:34.729074] [/yaskawa/motion_streaming_interface]: Aborting Trajectory. Failed to send point (#0): Invalid message (3) : Trajectory start position doesn't match current robot position (3011)

I managed to make the GP25 + positioner execute motions by putting all the joints in a single group:

```
---
topic_list:
  - name: robot
ns: ""
group: 0
joints:
   - yaskawa_joint_1_s
   - yaskawa_joint_2_l
   - yaskawa_joint_3_u
   - yaskawa_joint_4_r
   - yaskawa_joint_5_b
   - yaskawa_joint_6_t
   - yaskawa_joint_7_p
   - yaskawa_joint_8_y
```

Which suggests the issue isn't with the trajectory. The problem with doing this is that the trajectory timed out even though the robot physically moved. The /joint_state topic also contained 0 for the external axes even when they were jogged on the pendant.

I've tried applying the changes from #64 but this gave the same error. I've also attempted to apply #259 to my fork, but wasn't able to easily get the changes to take. Would the changes in #259 be expected to fix this issue, or are there any other things I can try?
